# Generated by Django 3.0.6 on 2020-06-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='নাম', max_length=50)),
                ('sex', models.CharField(choices=[(None, ''), ('Male', 'Male'), ('Female', 'Female')], default='', help_text='লিঙ্গ', max_length=10)),
                ('highest_education', models.CharField(blank=True, max_length=20, null=True)),
                ('highest_education_institute', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, help_text='পেশা', max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[(None, ''), ('Married', 'Married'), ('Unmarried', 'Unmarried')], default='', help_text='বৈবাহিক অবস্থা', max_length=10)),
                ('lives_in_village', models.CharField(choices=[(None, ''), ('Yes', 'Yes'), ('No', 'No')], default='', help_text='বর্তমানে গ্রামে থাকেন?', max_length=10)),
                ('alive', models.CharField(choices=[(None, ''), ('Alive', 'Alive'), ('Dead', 'Dead')], default='', help_text='জীবিত আছেন?', max_length=10)),
                ('bari', models.ForeignKey(default=None, help_text='বাড়ির নাম', on_delete=django.db.models.deletion.SET_DEFAULT, to='villagers.Bari')),
                ('father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='father_name', to='villagers.Villager')),
                ('grand_father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='grand_father_name', to='villagers.Villager')),
                ('grand_mother', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='grand_mother_name', to='villagers.Villager')),
                ('mother', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mother_name', to='villagers.Villager')),
                ('spouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='villagers.Villager')),
            ],
        ),
    ]
