# Generated by Django 3.0.5 on 2020-05-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='গ্রামের বাইরের লোক যুক্ত করবেন না', max_length=50)),
                ('highes_education', models.CharField(blank=True, max_length=20, null=True)),
                ('highes_education_institute', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, help_text='পেশা', max_length=100, null=True)),
                ('marital_status', models.BooleanField(help_text='বিবাহিত?')),
                ('sex', models.BooleanField(help_text='লিঙ্গ')),
                ('lives_in_village', models.BooleanField(default=True, help_text='বর্তমানে গ্রামে থাকেন?')),
                ('is_alive', models.BooleanField(default=True, help_text='জীবিত আছেন?')),
                ('bari', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='villagers.Bari')),
                ('father', models.ForeignKey(blank=True, default=None, help_text='গ্রামের হলে যুক্ত করুন', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='father_name', to='villagers.Villager')),
                ('grand_father', models.ForeignKey(blank=True, default=None, help_text='গ্রামের হলে যুক্ত করুন', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='grand_father_name', to='villagers.Villager')),
                ('grand_mother', models.ForeignKey(blank=True, default=None, help_text='গ্রামের হলে যুক্ত করুন', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='grand_mother_name', to='villagers.Villager')),
                ('mother', models.ForeignKey(blank=True, default=None, help_text='গ্রামের হলে যুক্ত করুন', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mother_name', to='villagers.Villager')),
                ('spouse', models.ForeignKey(blank=True, default=None, help_text='গ্রামের হলে যুক্ত করুন', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='villagers.Villager')),
            ],
        ),
    ]
