# Generated by Django 3.0.5 on 2020-05-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
