# Generated by Django 3.0.5 on 2020-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0005_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='sex',
            field=models.CharField(choices=[('----', None), ('Male', 'Male'), ('Female', 'Female')], default='----', help_text='লিঙ্গ', max_length=10),
        ),
    ]
