# Generated by Django 3.0.5 on 2020-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0006_auto_20200526_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='marital_status',
            field=models.CharField(choices=[(None, '----'), ('Married', 'Married'), ('Unmarried', 'Unmarried')], default='----', help_text='বিবাহিত', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='sex',
            field=models.CharField(choices=[(None, '----'), ('Male', 'Male'), ('Female', 'Female')], default='----', help_text='লিঙ্গ', max_length=10),
        ),
    ]
