# Generated by Django 3.0.5 on 2020-05-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0007_auto_20200526_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villager',
            old_name='highes_education',
            new_name='highest_education',
        ),
        migrations.RenameField(
            model_name='villager',
            old_name='highes_education_institute',
            new_name='highest_education_institute',
        ),
    ]
