# Generated by Django 3.0.5 on 2020-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0008_auto_20200526_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villager',
            name='is_alive',
        ),
        migrations.AddField(
            model_name='villager',
            name='alive',
            field=models.CharField(choices=[(None, '----'), ('Yes', 'Yes'), ('No', 'No')], default='----', help_text='জীবিত আছেন?', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='lives_in_village',
            field=models.CharField(choices=[(None, '----'), ('Yes', 'Yes'), ('No', 'No')], default='----', help_text='বর্তমানে গ্রামে থাকেন?', max_length=10),
        ),
    ]
