# Generated by Django 3.0.5 on 2020-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0009_auto_20200528_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='alive',
            field=models.CharField(choices=[(None, ''), ('Alive', 'Alive'), ('Dead', 'Dead')], default='', help_text='জীবিত আছেন?', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='lives_in_village',
            field=models.CharField(choices=[(None, ''), ('Yes', 'Yes'), ('No', 'No')], default='', help_text='বর্তমানে গ্রামে থাকেন?', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='marital_status',
            field=models.CharField(choices=[(None, ''), ('Married', 'Married'), ('Unmarried', 'Unmarried')], default='', help_text='বিবাহিত', max_length=10),
        ),
        migrations.AlterField(
            model_name='villager',
            name='sex',
            field=models.CharField(choices=[(None, ''), ('Male', 'Male'), ('Female', 'Female')], default='', help_text='লিঙ্গ', max_length=10),
        ),
    ]
